/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as generateTestsGenerateTestsRouteImport } from './routes/(generate-tests)/generate-tests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const generateTestsGenerateTestsRoute =
  generateTestsGenerateTestsRouteImport.update({
    id: '/(generate-tests)/generate-tests',
    path: '/generate-tests',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generate-tests': typeof generateTestsGenerateTestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generate-tests': typeof generateTestsGenerateTestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(generate-tests)/generate-tests': typeof generateTestsGenerateTestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/generate-tests'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/generate-tests'
  id: '__root__' | '/' | '/(generate-tests)/generate-tests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  generateTestsGenerateTestsRoute: typeof generateTestsGenerateTestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(generate-tests)/generate-tests': {
      id: '/(generate-tests)/generate-tests'
      path: '/generate-tests'
      fullPath: '/generate-tests'
      preLoaderRoute: typeof generateTestsGenerateTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  generateTestsGenerateTestsRoute: generateTestsGenerateTestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
